# Generated by Django 5.0.6 on 2024-06-01 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_course_created_at_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 11, 46, 51, 901947, tzinfo=datetime.timezone.utc)),
        ),
    ]
